### ISSUE TITLE
Move wptserve docs into web-platform-tests.org

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#14648]
web-platform-tests.org currently covers some features of wptserve, e.g. https://web-platform-tests.org/writing-tests/server-features.html , but there is still a large chunk missing (notably pipes, custom handlers, etc.) and can only be found in https://wptserve.readthedocs.io/en/latest/

@jgraham @gsnedders do you think we should move the documentation into GitHub Pages? If not, we should at least provide an easy-to-find pointer linking to the full docs.

**Comment by Hexcles** [comment]
Never mind there is already links to wptserve's doc in server-features.html, so my question is just: shall we combine the docs? If not, why?

**Comment by jgraham** [comment]
I'm happy for them to be combined, the current split is mostly historical accident.

**Comment by championshuttler** [comment]
I would like to work on it, can i take this up?

Thanks

**Comment by Hexcles** [comment]
@championshuttler feel free to send PR(s) :)

**Comment by foolip** [comment]
@jugglinmike will this be fixed by https://github.com/bocoup/wpt-docs/issues/2?

**Comment by jugglinmike** [comment]
That's my intention, but I'd like feedback from the interested parties before I say for certain.

**Comment by jugglinmike** [comment]
I believe we resolved this via gh-17039. @Hexcles as the reporter, would you mind confirming whether that patch satisfies your expectations?

**Comment by gsnedders** [comment]
We still have some things in `tools/wptserve/docs/`, mostly API docs. Given we're now using Sphinx, I feel like we should put them somewhere on WPT.org, even if not directly linked from the main page (some infrastructure development section on something).

**Comment by Hexcles** [comment]
> We still have some things in tools/wptserve/docs/, mostly API docs. Given we're now using Sphinx, I feel like we should put them somewhere on WPT.org, even if not directly linked from the main page (some infrastructure development section on something).

Agreed.

Also, it seems that the only way to get to the newly structured wptserve doc is: homepage -> server features -> Python handlers (the link is near the end of the page). Shall we perhaps increase the depth of the ToC?

**Comment by foolip** [comment]
@jugglinmike was this resolved by https://github.com/web-platform-tests/wpt/pull/17418?

**Comment by jugglinmike** [comment]
I think so, but [I've been wrong about that before](https://github.com/web-platform-tests/wpt/issues/14648#issuecomment-502910037). Once again deferring to @Hexcles. What do you think, Robert?

**Comment by Hexcles** [comment]
I'm happy with the current presentation of docs for wptserve. Thanks, @jugglinmike !

**Comment by jugglinmike** [comment]
Hooray!
