### ISSUE TITLE
Safari runs missing for week of May 15th, 2023

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt#40085]
No stable Safari results have been available [since May 15th](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari). [wpt.fyi run status](https://wpt.fyi/status) is not showing any recent invalid Safari runs. Not quite sure of the reason here. Creating this issue for visibility.

CC @gsnedders

**Comment by DanielRyanSmith** [comment]
Adds a heads-up, this is still a problem and no stable [aligned runs](https://wpt.fyi/runs?label=master&label=stable&max-count=100) (test results on the same hash for Chrome, Edge, Firefox, & Safari) have been produced since May 13th.

**Comment by foolip** [comment]
The most recent run is now from May 23.

**Comment by foolip** [comment]
Edge is failing too, I've filed https://github.com/web-platform-tests/wpt/issues/40300. But that Edge failing shouldn't affect Safari results being uploaded and vice versa.

**Comment by gsnedders** [comment]
We're getting a lot of:

> ##[error]We stopped hearing from agent Azure Pipelines 10. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610

…and there's nothing to suggest that somehow we're actually stopping the agent from running, or somehow ending up with Safari spinning or something. So theoretically something could've changed such that we're now starving the agent process of CPU, but it seems unlikely for that to have suddenly started?

**Comment by foolip** [comment]
@mustjab can you help with a contact on the Azure Pipelines team if @gsnedders needs it for debugging this issue?

**Comment by mustjab** [comment]
Best way to start would be to file an issue with azure-pipelines-agent team: https://github.com/microsoft/azure-pipelines-agent/issues/new/choose. I've looked through their open issues and didn't find any recent Mac issues, but this might be a related one: https://github.com/microsoft/azure-pipelines-agent/issues/3994

**Comment by foolip** [comment]
Thanks @mustjab!

**Comment by jgraham** [comment]
I've filed a new bug on Azure. Please let me know if I got any of the details wrong, or missed something important.

**Comment by mustjab** [comment]
@jgraham Looks like they've asked us to open issues on agent team instead, did you get a chance to file it?

https://github.com/microsoft/azure-pipelines-agent/issues/4313

**Comment by jgraham** [comment]
I filed https://github.com/actions/runner-images/issues/7754

**Comment by past** [comment]
@mustjab do you have any more context on the ongoing investigation that you can share?

**Comment by past** [comment]
It is still happening, [here is one case](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=104249&view=logs&j=90d4dc56-25a8-5b20-e853-c2d9d1fecc17) from today.

**Comment by gsnedders** [comment]
> I filed [actions/runner-images#7754](https://github.com/actions/runner-images/issues/7754)

From there, the internal issue has been resolved, and it seems like things have been much better over the last few days (comparable to where we were on the `macos-12` images).

**Comment by gsnedders** [comment]
it's gone back to being less reliable, but as mentioned in the other issue:

>  fix is to be delivered around mid-august (reason for being better right now is not very clear)

**Comment by past** [comment]
The fix seems to be deployed and working reasonably well now, shall we close this?

**Comment by past** [comment]
@mustjab any further updates on the effort to fix this? The link from Sam's comment above still shows frequent failures.

**Comment by gsnedders** [comment]
@past A fair percentage of the failures are Edge, or caused by macOS bugs. https://wpt.fyi/runs?label=master&label=experimental&aligned and https://wpt.fyi/runs?label=master&label=stable&aligned both show plenty of recent aligned runs, so I'm not too concerned at this point. I vote we close this?

**Comment by past** [comment]
Sounds good to me, we can open a new one if needed.
